# Generated by Django 3.1.7 on 2021-05-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qty',
            new_name='quantiy',
        ),
    ]
