# Generated by Django 3.1.7 on 2021-05-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20210510_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
